name: Push site to linux vm

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - run: run build
            - run: scp -r dist/* mateo@51.120.3.115:/var/www/souto.no/