name: Push site to linux vm

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./site

        steps:
            - uses: actions/checkout@v3
    
            - uses: actions/setup-node@v3
    
            - uses: bahmutov/npm-install@v1
              with:
                working-directory: site
    
            - run: npm run build
    
            - uses: actions/upload-artifact@v3
              with:
                name: production-files
                path: ./dist/*

            - uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                source: "site/dist/*.html, site/dist/*.svg, site/dist/assets/*.js, site/dist/assets/*.css"
                target: /var/www/souto.no/